#!/usr/bin/env bash

# shellcheck source=collection-scripts/common.sh
source "$(dirname "$0")/common.sh"
get_log_collection_args

# shellcheck disable=SC2086
oc adm inspect ${log_collection_args} --dest-dir=must-gather -A olm
