#!/bin/bash

# Resource List
resources=()

# machine-api resources
machineresources=()

# Cluster Version Information
resources+=(clusterversion ns/openshift-cluster-version)

# Operator Resources
resources+=(clusteroperators)

# Certificate Resources
resources+=(certificatesigningrequests)

# MCO/Node Resources
resources+=(nodes machineconfigs machineconfigpools)

# machine-api resources
machineresources+=(machines machinesets)

# Namespaces/Project Resources
resources+=(ns/default ns/openshift ns/kube-system ns/openshift-etcd)

# Storage Resources
resources+=(storageclasses persistentvolumes volumeattachments)

# Networking Resources
resources+=(clusternetworks hostsubnets)

# Autoscaler Resources
machineresources+=(clusterautoscaler machineautoscaler)

# Run the Collection of Resources using must-gather
for resource in ${resources[@]}; do
    /usr/bin/openshift-must-gather inspect ${resource}
done

# Run the Collection of MachineAPIResources using must-gather
for resource in ${machineresources[@]}; do
    /usr/bin/openshift-must-gather inspect ${resource} --namespace openshift-machine-api
done

# Collect System Audit Logs
/usr/bin/gather_audit_logs

# Gather Service Logs (using a suplamental Script); Scoped to Masters.
/usr/bin/gather_service_logs master
