#!/bin/bash
BASE_COLLECTION_PATH="must-gather"
NMSTATE_NS="$(oc get subs -A -o template --template '{{range .items}}{{if eq .spec.name "kubernetes-nmstate-operator"}}{{.metadata.namespace}}{{"\n"}}{{end}}{{end}}')"

if [ -z "${NMSTATE_NS}" ]; then
    echo "INFO: NMState not detected. Skipping."
    exit 0
fi

if [[ "$(echo "${NMSTATE_NS}" | wc -l)">1 ]]; then
    echo "ERROR: found more than one kubernetes-nmstate-operator subscription. Exiting."
    exit 1
fi

function get_nmstate_crs() {
    declare -a NMSTATE_CRDS=("nmstates" "nodenetworkconfigurationenactments" "nodenetworkconfigurationpolicies" "nodenetworkstates")

    for CRD in "${NMSTATE_CRDS[@]}"; do
        oc adm inspect --dest-dir "${BASE_COLLECTION_PATH}" "${CRD}"
    done
}

oc adm inspect --dest-dir "${BASE_COLLECTION_PATH}" "ns/${NMSTATE_NS}"
get_nmstate_crs

# force disk flush to ensure that all data gathered is accessible in the copy container
sync
