#!/bin/bash

# This script is not supposed to be executed manually. It is used from
# the gather_ppc collection script.

pod=$1
NAMESPACE=$2
node=$3
NODE_PATH=$4

echo "Collecting performance related data for node $node"

oc exec $pod -n $NAMESPACE -- lspci -nvv > $NODE_PATH/lspci
oc exec $pod -n $NAMESPACE -- lscpu -e > $NODE_PATH/lscpu
oc exec $pod -n $NAMESPACE -- cat /proc/cmdline > $NODE_PATH/proc_cmdline
oc exec $pod -n $NAMESPACE -- dmesg > $NODE_PATH/dmesg
oc exec $pod -n $NAMESPACE -- ethtool -k eth0 > $NODE_PATH/ethtool_features
oc exec $pod -n $NAMESPACE -- ethtool -l eth0 > $NODE_PATH/ethtool_channels

oc exec $pod -n $NAMESPACE -- gather-sysinfo --json cpuaff --procfs=/host/proc --sysfs=/host/sys > $NODE_PATH/cpu_affinities.json
oc exec $pod -n $NAMESPACE -- gather-sysinfo --json irqaff --procfs=/host/proc --sysfs=/host/sys > $NODE_PATH/irq_affinities.json
oc exec $pod -n $NAMESPACE -- gather-sysinfo --json podres --socket-path=unix:///host/podresources/kubelet.sock > $NODE_PATH/podresources.json

oc exec $pod -n $NAMESPACE -- gather-sysinfo snapshot --debug --root=/host --output=- > $NODE_PATH/sysinfo.tgz 2> $NODE_PATH/sysinfo.log
oc exec $pod -n $NAMESPACE -- gather-sysinfo podinfo --node-name $node > $NODE_PATH/pods_info.json
