#!/bin/bash

source $(dirname "$0")/common.sh
BASE_COLLECTION_PATH="must-gather"
get_operator_ns "kubevirt-hyperconverged"
VIRTUALIZATION_PATH="${BASE_COLLECTION_PATH}/virtualization"
mkdir -p "${VIRTUALIZATION_PATH}"

function collect_running_vms_count() {
  oc get vmi --all-namespaces -o=jsonpath='{.items[?(@.status.phase=="Running")].metadata.name}' | wc -w > "${VIRTUALIZATION_PATH}/running_vms_count.txt"
}

collect_running_vms_count
