#!/bin/bash

# shellcheck source=collection-scripts/common.sh
source "$(dirname "$0")/common.sh"
BASE_COLLECTION_PATH="must-gather"
get_operator_ns "kubernetes-nmstate-operator"
get_log_collection_args

inspect_operator_ns "${operator_ns}"
inspect_crds_cluster nmstates nodenetworkconfigurationenactments nodenetworkconfigurationpolicies nodenetworkstates

# force disk flush to ensure that all data gathered is accessible in the copy container
sync
