#!/bin/bash
. collect_service_logs

BASE_COLLECTION_PATH="/must-gather"
ROLES=${1:-master}         ### Defaults to only collecting things from Masters

# Service Lists
GENERAL_SERVICES=(kubelet crio machine-config-daemon-firstboot machine-config-daemon-host)
MASTER_SERVICES+=(${2:-"${GENERAL_SERVICES[@]}"})
MASTER_SERVICES+=()        ### Placeholder to extend Master only services
NODE_SERVICES+=(${2:-"${GENERAL_SERVICES[@]}"})
NODE_SERVICES+=()          ### Placeholder to extend Node only services

# Collect System Service Logs
SERVICE_LOG_PATH="${BASE_COLLECTION_PATH}/host_service_logs/"

if [[ $ROLES == "master" ]]; then
    collect_service_logs master ${MASTER_SERVICES[@]}
elif [[ $ROLES == "worker" ]]; then
    collect_service_logs worker ${NODE_SERVICES[@]}
elif [[ $ROLES == "master,worker" ]] || [[ $ROLES == "worker,master" ]] ; then
    collect_service_logs master ${MASTER_SERVICES[@]}
    collect_service_logs worker ${NODE_SERVICES[@]}
else
    echo "Error: no role supplied or an invalid role was supplied." >&2
    echo "Error: valid roles are 'master', 'worker', 'master,worker' or 'worker,master'." >&2
fi

# force disk flush to ensure that all data gathered is accessible in the copy container
sync
