#!/bin/bash

source $(dirname "$0")/common.sh
BASE_COLLECTION_PATH="must-gather"
get_operator_ns "nfd"
get_log_collection_args

echo "INFO: Collecting NFD Data in namespace ${operator_ns}"
inspect_operator_ns "${operator_ns}"
inspect_crds_namespaced "${operator_ns}" nodefeaturediscoveries nodefeaturegroups nodefeaturerules nodefeatures

# force disk flush to ensure that all data gathered is accessible in the copy container
sync
