#!/bin/bash

source $(dirname "$0")/common.sh
get_log_collection_args

BASE_COLLECTION_PATH="/must-gather"
WINDOWS_NODE_LOGS=$BASE_COLLECTION_PATH/host_service_logs/windows

# Logfile list
LOGS=(kube-proxy/kube-proxy.log)
LOGS+=(hybrid-overlay/hybrid-overlay.log)
LOGS+=(kubelet/kubelet.log)
LOGS+=(containerd/containerd.log)
LOGS+=(wicd/windows-instance-config-daemon.exe.INFO wicd/windows-instance-config-daemon.exe.ERROR wicd/windows-instance-config-daemon.exe.WARNING)
LOGS+=(csi-proxy/csi-proxy.log)

# if the cluster has no Windows nodes skip this script
WIN_NODES=$(/usr/bin/oc get no -l kubernetes.io/os=windows)
if [ -z "$WIN_NODES" ]; then
    exit 0
fi

PIDS=()
echo INFO: Collecting logs for all Windows nodes
for log in ${LOGS[@]}; do
    LOG_FILE_DIR=${WINDOWS_NODE_LOGS}/log_files/$(dirname $log)
    mkdir -p ${LOG_FILE_DIR}
    /usr/bin/oc adm node-logs ${node_log_collection_args:+"$node_log_collection_args"} -l kubernetes.io/os=windows --path=$log > ${LOG_FILE_DIR}/$(basename $log) &
    PIDS+=($!)
done
wait ${PIDS[@]}

# force disk flush to ensure that all data gathered is accessible in the copy container
sync
