#!/bin/bash

# shellcheck source=collection-scripts/common.sh
source "$(dirname "$0")/common.sh"
BASE_COLLECTION_PATH="must-gather"
get_operator_ns "ingress-node-firewall"
get_log_collection_args

inspect_operator_ns "${operator_ns}"
inspect_crds_namespaced "${operator_ns}" ingressnodefirewallconfigs ingressnodefirewallnodestates
inspect_crds_cluster ingressnodefirewalls

# force disk flush to ensure that all data gathered is accessible in the copy container
sync
