#!/bin/bash

source $(dirname "$0")/common.sh
BASE_COLLECTION_PATH="must-gather"
get_operator_ns "kubernetes-nmstate-operator"

function get_nmstate_crs() {
    declare -a NMSTATE_CRDS=("nmstates" "nodenetworkconfigurationenactments" "nodenetworkconfigurationpolicies" "nodenetworkstates")

    for CRD in "${NMSTATE_CRDS[@]}"; do
        oc adm inspect --dest-dir "${BASE_COLLECTION_PATH}" "${CRD}"
    done
}

oc adm inspect --dest-dir "${BASE_COLLECTION_PATH}" "ns/${operator_ns}"
get_nmstate_crs

# force disk flush to ensure that all data gathered is accessible in the copy container
sync
