#!/bin/bash

# safeguards
set -o nounset
set -o errexit
set -o pipefail

# shellcheck source=collection-scripts/monitoring_common.sh
source "$(dirname "$0")/monitoring_common.sh"

metrics_gather "$@"
