#!/usr/bin/env bash

function version() {
  # get version from image

  version=$(oc get ClusterVersion -o jsonpath='{.items[0].status.history[0].version}{"\n"}')

  # if version not found, fallback to imageID
  [ -z "${version}" ] && version=$(oc status | grep '^pod.*runs' | sed -r -e 's/^pod.*runs //')

  # if version still not found, use Unknown
  [ -z "${version}" ] && version="Unknown"

  echo ${version}
}
